// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaDumpsterAPI.Data;

namespace RaDumpsterAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211028023547_Table-Creation")]
    partial class TableCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RaDumpsterAPI.Models.Dumpster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DumpsterCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DumpsterStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DumpsterCategoryId");

                    b.HasIndex("DumpsterStatusId");

                    b.ToTable("Dumpster");
                });

            modelBuilder.Entity("RaDumpsterAPI.Models.DumpsterCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DumpsterCategory");
                });

            modelBuilder.Entity("RaDumpsterAPI.Models.DumpsterPriceDistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DistanceEnd")
                        .HasColumnType("int");

                    b.Property<int>("DistanceStart")
                        .HasColumnType("int");

                    b.Property<int>("DumpsterCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("DumpsterCategoryId");

                    b.ToTable("DumpsterPriceDistance");
                });

            modelBuilder.Entity("RaDumpsterAPI.Models.DumpsterStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DumpsterStatus");
                });

            modelBuilder.Entity("RaDumpsterAPI.Models.Dumpster", b =>
                {
                    b.HasOne("RaDumpsterAPI.Models.DumpsterCategory", "DumpsterCategory")
                        .WithMany()
                        .HasForeignKey("DumpsterCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaDumpsterAPI.Models.DumpsterStatus", "DumpsterStatus")
                        .WithMany()
                        .HasForeignKey("DumpsterStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DumpsterCategory");

                    b.Navigation("DumpsterStatus");
                });

            modelBuilder.Entity("RaDumpsterAPI.Models.DumpsterPriceDistance", b =>
                {
                    b.HasOne("RaDumpsterAPI.Models.DumpsterCategory", "DumpsterCategory")
                        .WithMany()
                        .HasForeignKey("DumpsterCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DumpsterCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
